#!/usr/bin/env bash
#
# run-goals.sh — drive every /goal in this plugin's goals/ tree via codex exec
#
# Generated by the wp-requirements-to-goals skill. Iterates goals/NN-*/ in
# lexical order and runs one `codex exec` per folder with the standard /goal
# prompt. /goal follows VERIFY.md inline, so a single exec per goal is enough
# to produce evidence-based completion.
#
# Usage:
#   ./run-goals.sh                 Run every goal in order (default)
#   ./run-goals.sh --from 03       Resume from goal 03 (skip 00–02)
#   ./run-goals.sh --to   05       Stop after goal 05
#   ./run-goals.sh --only 04       Run only goal 04
#   ./run-goals.sh --dry-run       Print what would run, don't invoke codex
#   ./run-goals.sh --no-env        Skip the wp-env start/stop bracket
#   ./run-goals.sh --quiet         Don't tee codex output to the terminal (log only)
#   ./run-goals.sh --no-commit     Skip auto-commit after each successful goal
#   ./run-goals.sh --allow-dirty   Run even if the working tree has uncommitted changes
#   ./run-goals.sh -h | --help     Show this help
#
# Environment:
#   CODEX_SANDBOX    Sandbox mode for codex exec (default: danger-full-access)
#   CODEX_APPROVAL   Approval policy for codex exec (default: never)
#
# Requirements:
#   codex CLI ≥ the version that ships `codex exec` (install: npm i -g @openai/codex)
#   Authenticated codex session: `codex login` once, or CODEX_API_KEY in env
#   Docker running (wp-env spins WordPress in a container)
#
# Why danger-full-access by default:
#   /goal verification runs `wp-env`, `playwright-cli`, and `npm install` —
#   these touch Docker, the network, and Unix sockets, which workspace-write
#   blocks. Override with CODEX_SANDBOX=workspace-write if you don't need
#   container or browser steps in this run.
#
# Failure handling:
#   On any failing goal the script exits with codex's exit code and prints a
#   resume command. wp-env is left running so you can debug interactively.

set -euo pipefail

# --- defaults ---
SANDBOX="${CODEX_SANDBOX:-danger-full-access}"
APPROVAL="${CODEX_APPROVAL:-never}"
FROM=""
TO=""
ONLY=""
DRY_RUN=false
NO_ENV=false
QUIET=false
COMMIT=true
ALLOW_DIRTY=false
LOG_DIR="logs/goals"

usage() {
  sed -n '2,/^$/p' "$0" | sed -E 's/^# ?//' | sed '/^!\/usr\/bin\/env/d'
}

# --- parse args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --from)    FROM="$2"; shift 2 ;;
    --to)      TO="$2"; shift 2 ;;
    --only)    ONLY="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --no-env)  NO_ENV=true; shift ;;
    --quiet)   QUIET=true; shift ;;
    --no-commit)   COMMIT=false; shift ;;
    --allow-dirty) ALLOW_DIRTY=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# Normalize numeric filters to zero-padded two-digit form so --from 3 == --from 03.
[[ -n "$FROM" ]] && FROM=$(printf '%02d' "$((10#$FROM))" 2>/dev/null || echo "$FROM")
[[ -n "$TO"   ]] && TO=$(printf '%02d' "$((10#$TO))"   2>/dev/null || echo "$TO")
[[ -n "$ONLY" ]] && ONLY=$(printf '%02d' "$((10#$ONLY))" 2>/dev/null || echo "$ONLY")

# --- preflight ---
if [[ ! -d goals ]]; then
  echo "✗ No goals/ directory found. Run this from the plugin project root." >&2
  exit 1
fi

if ! command -v codex >/dev/null 2>&1; then
  echo "✗ codex CLI not found in PATH. Install with: npm install -g @openai/codex" >&2
  exit 1
fi

# Scan every generated test plan for banned uninstall tokens. Running these
# operations against the shared dev wp-env tears down the database the next
# goal depends on and leaves wp-env unusable. Uninstall hygiene belongs in the
# integration goal's disposable-env protocol (see goals/<NN>-integration/VERIFY.md
# § "Uninstall hygiene check"), never inside any test_plan.md.
BANNED_TOKENS=(
  'wp plugin uninstall'
  'register_uninstall_hook'
  'uninstall\.php'
  'wp db reset'
  'DROP TABLE'
)
banned_hits=""
for plan in goals/*/tests/test_plan.md; do
  [[ -f "$plan" ]] || continue
  for token in "${BANNED_TOKENS[@]}"; do
    if grep -nE "$token" "$plan" >/dev/null 2>&1; then
      banned_hits="$banned_hits$(grep -nE "$token" "$plan" | sed "s|^|$plan:|")\n"
    fi
  done
done
if [[ -n "$banned_hits" ]]; then
  echo "✗ Preflight: test plans contain banned uninstall tokens against the shared dev wp-env." >&2
  echo "  These operations destroy state that subsequent goals depend on. Move them to" >&2
  echo "  the integration goal's disposable-env protocol or remove them entirely." >&2
  echo "" >&2
  echo -e "  $banned_hits" >&2
  exit 1
fi

# Disable commit logic if we're not inside a git repo.
if [[ "$COMMIT" == true ]] && ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "⚠ Not inside a git repository — auto-commit disabled." >&2
  COMMIT=false
fi

# Refuse to start with a dirty tree when auto-commit is on; otherwise the first
# auto-commit would bundle unrelated WIP into a goal commit.
if [[ "$COMMIT" == true && "$DRY_RUN" == false && "$ALLOW_DIRTY" == false ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "✗ Working tree has uncommitted changes. Commit or stash first, or re-run with --allow-dirty." >&2
    git status --short >&2
    exit 1
  fi
fi

# --- discover goals ---
GOALS=()
for dir in goals/[0-9][0-9]-*/; do
  [[ -d "$dir" ]] || continue
  GOALS+=("$(basename "$dir")")
done

if [[ ${#GOALS[@]} -eq 0 ]]; then
  echo "✗ No goal folders found under goals/. Expected goals/00-*, goals/01-*, …" >&2
  exit 1
fi

# --- filter helper ---
should_run() {
  local num="${1:0:2}"
  if [[ -n "$ONLY" ]] && [[ "$num" != "$ONLY" ]]; then return 1; fi
  if [[ -n "$FROM" ]] && [[ "$num" < "$FROM" ]]; then return 1; fi
  if [[ -n "$TO"   ]] && [[ "$num" > "$TO"   ]]; then return 1; fi
  return 0
}

# --- decide wp-env bracketing ---
# Full sweeps bracket wp-env. Partial runs (--from / --to / --only) assume the
# user already has the environment up and skip the bracket. --no-env forces
# skip regardless. --dry-run never touches wp-env.
BRACKET_ENV=true
[[ "$NO_ENV" == true || "$DRY_RUN" == true ]] && BRACKET_ENV=false
[[ -n "$FROM" || -n "$TO" || -n "$ONLY" ]] && BRACKET_ENV=false

mkdir -p "$LOG_DIR"
START_RUN=$(date +%s)
SCOPED=0
SKIPPED=0

# --- start wp-env if applicable ---
if [[ "$BRACKET_ENV" == true ]]; then
  echo "→ Starting wp-env (npm run env:start)..."
  npm run env:start
fi

# --- main loop ---
for goal in "${GOALS[@]}"; do
  if ! should_run "$goal"; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi
  SCOPED=$((SCOPED + 1))

  goal_dir="goals/$goal"
  prompt="/goal Complete $goal_dir/GOAL.md. Use $goal_dir/VERIFY.md as the verification contract. Update $goal_dir/PROGRESS.md continuously. Treat uncertainty as incomplete."

  ts=$(date +%Y%m%d-%H%M%S)
  log_file="$LOG_DIR/${goal}-${ts}.jsonl"
  final_file="$LOG_DIR/${goal}-${ts}-final.md"

  echo ""
  echo "═══════════════════════════════════════════════════════════"
  echo "  Goal:     $goal"
  echo "  Log:      $log_file"
  echo "  Sandbox:  $SANDBOX"
  echo "  Approval: $APPROVAL"
  echo "═══════════════════════════════════════════════════════════"

  cmd=(codex exec
       --sandbox       "$SANDBOX"
       -c              "approval_policy=$APPROVAL"
       --json
       -o              "$final_file"
       "$prompt")

  if [[ "$DRY_RUN" == true ]]; then
    printf "  [dry-run]"
    for arg in "${cmd[@]}"; do printf " %q" "$arg"; done
    printf "\n"
    continue
  fi

  start=$(date +%s)
  if [[ "$QUIET" == true ]]; then
    if "${cmd[@]}" > "$log_file" 2>&1; then rc=0; else rc=$?; fi
  else
    if "${cmd[@]}" 2>&1 | tee "$log_file"; then rc=0; else rc=${PIPESTATUS[0]}; fi
  fi
  if [[ $rc -eq 0 ]]; then
    elapsed=$(($(date +%s) - start))
    printf "  ✓ Goal %s completed in %dm %ds\n" "$goal" $((elapsed/60)) $((elapsed%60))
    if [[ -f "$final_file" ]]; then
      printf "\n---\nGoal %s completed in %dm %ds\n" \
             "$goal" $((elapsed/60)) $((elapsed%60)) >> "$final_file"
    fi
    if [[ "$COMMIT" == true ]]; then
      git add -A
      if git diff --cached --quiet; then
        printf "  ℹ No changes to commit for %s\n" "$goal"
      else
        commit_subject="goal($goal): complete in $((elapsed/60))m $((elapsed%60))s"
        commit_body="Final message: $final_file"
        git commit -m "$commit_subject" -m "$commit_body" >/dev/null
        printf "  ✓ Committed: %s\n" "$commit_subject"
      fi
    fi
  else
    elapsed=$(($(date +%s) - start))
    num="${goal:0:2}"
    echo ""
    printf "  ✗ Goal %s FAILED after %dm %ds (codex exit %d)\n" \
           "$goal" $((elapsed/60)) $((elapsed%60)) "$rc"
    echo "    Log:           $log_file"
    echo "    Final message: $final_file"
    echo ""
    echo "  Resume after fixing with:"
    echo "    $0 --from $num"
    echo ""
    echo "  wp-env is still running. Inspect with:"
    echo "    npm run env:cli -- option get siteurl"
    echo "  Tear down manually when done: npm run env:stop"
    exit "$rc"
  fi
done

# --- stop wp-env on clean exit ---
if [[ "$BRACKET_ENV" == true && "$DRY_RUN" == false ]]; then
  echo ""
  echo "→ Stopping wp-env (npm run env:stop)..."
  npm run env:stop
fi

total_elapsed=$(($(date +%s) - START_RUN))
echo ""
echo "═══════════════════════════════════════════════════════════"
if [[ "$DRY_RUN" == true ]]; then
  printf "  Dry run complete. %d goal(s) would run, %d skipped.\n" "$SCOPED" "$SKIPPED"
else
  printf "  ✓ %d goal(s) completed in %dm %ds (%d skipped).\n" \
         "$SCOPED" $((total_elapsed/60)) $((total_elapsed%60)) "$SKIPPED"
fi
echo "═══════════════════════════════════════════════════════════"
